# service deploy kubenews

apiVersion: v1
kind: Service
metadata:
  name: kubenews
spec:
  selector:
    app: kubenews
  ports:
  - port: 80
    targetPort: 8080 # porta que a aplicação é exposta
    nodePort: 30000 # porta kk3d cluster create cluster --servers 1 --agents 2 -p "30000:30000@loadbalancer" 3d 
  type: NodePort